### ISSUE TITLE
Create new module for functions in script.py

### ISSUE THREAD

**Issue by thescriptninja** [thescriptninja/pytodo#10]
Currently `script.py` contains a lot of functions, many of which can be moved to another file for better code readability and structure

**Comment by singh-yashwant** [comment]
I am working on this.
Any suggestions how the final structure should look like?

**Comment by thescriptninja** [comment]
Hi @singh-yashwant! Currently, the `script.py` file contains a lot of functions that can be called from another module. What I would suggest is to define all the functions in a file called `modules.py` and import the functions into `script.py` that will only contain the `main()` function. Let me know if you have any difficulty working on this.
