### ISSUE TITLE
pipenv install does not work

### ISSUE THREAD

**Issue by thisisshub** [thescriptninja/pytodo#13]
`pipenv install` does not work. 
I followed the steps, 
- `pipenv shell` after cloning the repository. It setups the virtualenv then
- `pipenv install` returns the error output [1]

I fiddled around the internet and found out [--skip-lock](https://github.com/pypa/pipenv/issues/1579#issue-303072931) command, the whole as `pipenv install --skip-lock` does not work either.It returns the error output [2]

### [1]
```
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmpskr1rjsdbuild/dotenv/
```
### [2]
```
'ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.']
ERROR: ERROR: Package installation failed...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:04
```

I believe the best way to resolve this would be to use the old way of using a `requirements.txt` file.

**Comment by amitkr936** [comment]
For me im getting the error
``TypeError: 'module' object is not callable``
i am using python 3

**Comment by thisisshub** [comment]
> for the 1st command im getting the error
> `TypeError: 'module' object is not callable`
> i am using python 3

You should be using python 3.7. It's mentioned in the pip file.

**Comment by thescriptninja** [comment]
I have added the `requirements.txt` file. Since we do not have many dependencies, it should suffice for the moment

**Comment by thisisshub** [comment]
> I have added the `requirements.txt` file. Since we do not have many dependencies, it should suffice for the moment

Thanks! the `requirements.txt` did the trick
