### ISSUE TITLE
Add --quotes option

### ISSUE THREAD

**Issue by thescriptninja** [thescriptninja/pytodo#17]
Currently, the app serves random quotes selected from `quotes.txt`. However, there should be an option to disable quotes.

**Comment by janish1999** [comment]
Can I work on this issue?

**Comment by thisisshub** [comment]
@thescriptninja  Surely I can look into this, but let's first @janish1999 try because he got here first. I'll look into some other matter for the time being, if you have any suggestion please share them.

**Comment by thescriptninja** [comment]
@janish1999 please go ahead :+1: Looking forward to your contribution :smile:
