### ISSUE TITLE
update --edit feature

### ISSUE THREAD

**Issue by singh-yashwant** [thescriptninja/pytodo#20]
Currently --edit feature can only be used to update the name of a todo, however it can be modified to also edit the due date of the todo

**Comment by thescriptninja** [comment]
Thanks! That's a great idea. How do you suggest we implement it?

**Comment by singh-yashwant** [comment]
I suppose when - - edit is called we can ask user 2 questions 1 by 1 whether he want to edit the title than we can ask whether he want to edit the due date
